fever_common = '/local/fever-common'
index_dir = '/hexaf/fever/data'
results_dir = '/hexaf/fever/results'
wiki_dir = '/local/fever-common/data/wiki-pages'
reader = '/hexaf/fever/results/base+sampling2+evscores+rerank+train+dev+test-shared_test.ver0727_newaggr_submission/reader'
fever_dir = '/hexaf/fever'
jack_dir = '/hexaf/jack'
